version: '3.9'

services:

  samba:
      image: dperson/samba
      container_name: samba
      restart: unless-stopped
      command: -u "${USER};${SAMBAPASS}" -w "lan" -s "sambita;/share/data;yes;no;yes" -W -S 
      stdin_open: true
      tty: true
      read_only: true
      environment:
         - TZ=${TZ}
         - PUID=${PUID}
         - PGID=${PGID}
      volumes:
         - ${STORAGE}:/share/data:z
         - ${TMP}:/tmp:z
      ports:
         - "137:137/udp"
         - "138:138/udp"
         - "139:139/tcp"
         - "445:445/tcp"
