version: '3.9'

services:

  samba:
      image: dperson/samba
      container_name: samba
      restart: unless-stopped
      command: '-s "completed;/completed;yes;no;no" -s "blackhole;blackhole;yes;no;yes" -u "${USER};${SAMBAPASS}" -w "lan" -p'
      # command: '-s "downloads;/downloads" -s "completed;/completed;yes;no;no" -u "${USER};${SAMBAPASS}" -w "lan" -p'
      stdin_open: true
      tty: true
      read_only: true
      environment:
         - TZ=${TZ}
         - PUID=${PUID}
         - PGID=${PGID}
      volumes:
         - ${DOWNLOADS}/blackhole:/blackhole:z
         - ${COMPLETED}:/completed:z
         - ${TMP}:/tmp:z
      ports:
         - "137:137/udp"
         - "138:138/udp"
         - "139:139/tcp"
         - "445:445/tcp"
