version: '3.9'

services:

  samba:
      image: dperson/samba
      container_name: samba
      restart: unless-stopped
      command: '-s "storage;/storage/;yes;no;no" -u "eduzen;h0l4nd4!" -w "lan" -p'
      stdin_open: true
      tty: true
      read_only: true
      environment:
         - TZ=Europe/Amsterdam
         - PUID=1001
         - PGID=1001
      volumes:
          - "/home/eduzen/storage:/storage:ro"
          - /tmp:/tmp
      ports:
         - "137:137/udp"
         - "138:138/udp"
         - "139:139/tcp"
         - "445:445/tcp"
