version: "3.9"

networks:
  traefik_default:
    external: true

services:
  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    volumes:
      - ./configs/radarr:/config
      - /home/eduzen/mounts/storage/media-center:/media-center:z
    expose:
      - 8989
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.huis.win`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - traefik_default

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - DELUGE_LOGLEVEL=error #optional
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./configs/deluge:/config
      - /home/eduzen/mounts/storage/media-center/downloads:/downloads:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qb.rule=Host(`deluge.huis.win`)"
      - "traefik.http.services.qb.loadbalancer.server.port=8112"
    networks:
      - traefik_default
