version: "3.8"

services:
  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    volumes:
      - ./config:/config
      - ${DOWNLOADS}:/downloads
      - ${TV}:/tv
    ports:
      - 8989:8989
    expose:
      - 8989
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.huis`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
