version: "3.9"

networks:
  traefik_default:
    external: true

services:
  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    volumes:
      - ./configs/radarr:/config
      - /home/eduzen/mounts/storage/media-center:/media-center:z
    expose:
      - 8989
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.huis`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - traefik_default

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - PASS=${QBPASSWORD}
      # - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=admin #optional
    volumes:
      - ./configs/transmission:/config
      - /home/eduzen/mounts/storage/media-center/downloads:/downloads:z
    ports:
      - 51413:51413
      - 51413:51413/udp
    expose:
      - "9091"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trans.rule=Host(`torrent.series.huis`)"
      - "traefik.http.services.trans.loadbalancer.server.port=9091"
    networks:
      - traefik_default

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    expose:
      - 9696
    volumes:
      - ./configs/prowlarr:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.p.rule=Host(`prowlarr.series.huis`)"
      - "traefik.http.services.p.loadbalancer.server.port=9696"
    networks:
      - traefik_default
