version: "3.8"

services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=80
    expose:
      - "80"
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./config:/config/qBittorrent:z
      - ${DOWNLOADS}:/downloads:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qb.rule=Host(`qb.${DOMAIN}`)"
      - "traefik.http.routers.qb.entrypoints=websecure"
      - "traefik.http.routers.qb.tls.certresolver=myresolver"
      - "traefik.qb.headers.contentTypeNosniff=true"
      - "traefik.qb.headers.forceSTSHeader=true"
      - "traefik.qb.headers.browserXSSFilter=true"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
