version: "3.8"

networks:
  traefik_default:
    external: true

services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=80
    expose:
      - "80"
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./config:/config/qBittorrent:z
      - ${DOWNLOADS}:/downloads:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qb.rule=Host(`qb.huis`)||Host(`torrent.huis`)"
      - "traefik.http.services.qb.loadbalancer.server.port=80"
    networks:
      - traefik_default
