version: "3.8"

services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:unstable-version-4.4.0202106140855-7320-2bd5aca3aubuntu20.04.1
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK=022
      - WEBUI_PORT=80
    expose:
      - "80"
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /media/eduzen/storage/media-center/configs/qb:/config:z
      - /media/eduzen/storage/media-center/downloads:/downloads:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qb.rule=Host(`qb.eduzen.duckdns.org`)"
      - "traefik.http.routers.qb.entrypoints=websecure"
      - "traefik.http.routers.qb.tls.certresolver=myresolver"
      - "traefik.qb.headers.contentTypeNosniff=true"
      - "traefik.qb.headers.forceSTSHeader=true"
      - "traefik.qb.headers.browserXSSFilter=true"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
