version: "3.8"

services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Amsterdam
      - UMASK=022
      - WEBUI_PORT=80
    expose:
      - "80"
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./config:/config/qBittorrent:z
      - ${DOWNLOADS}:/downloads:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qb.rule=Host(`qb.t480.local`)"
      - "traefik.http.services.qb.loadbalancer.server.port=80"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
