version: "3"
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: ddclient
    environment:
      - API_KEY=${CLOUDFLARE_API_KEY}
      - ZONE=eduzen.ar
      - SUBDOMAIN=tv
      - PROXIED=true
      - CRON="@daily"
    volumes:
      - ./config/:/config
    restart: unless-stopped
