version: "3.8"

services:

  readarr:
    image: ghcr.io/linuxserver/readarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    volumes:
      - ./config:/config
      - ${BOOKS}:/books:z
      - ${DOWNLOADS}:/downloads:z
    ports:
      - 8787:8787

