version: "3.9"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    ports:
      - 9696:9696
    volumes:
      - ./config:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
