version: "3.9"

networks:
  traefik_default:
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    expose:
      - 9696
    volumes:
      - ./config:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.huis`)"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    networks:
      - traefik_default
