version: "3.9"

services:
  duckdns:
    image: ghcr.io/linuxserver/duckdn:latest
    container_name: duckdns
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS}
      - TOKEN=${TOKEN}
      - PUID=${PUID}
      - PGID=${GPID}
      - LOG_FILE=true
    volumes:
      - ./config:/config
