version: "3.9"

services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    privileged: true
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - VERSION=docker
    expose:
      - 32400
    volumes:
      - ${CONFIGS}/plex:/config
      - ${TMP}/plex:/transcode
      - ${MOVIES}:/movies:z
      - ${TV}:/tv:z
      - ${MUSIC}:/music:z
      - ${DOWNLOADS}/downloads:z
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls.certresolver=myresolver"
      - "traefik.plex.headers.contentTypeNosniff=true"
      - "traefik.plex.headers.forceSTSHeader=true"
      - "traefik.plex.headers.browserXSSFilter=true"

networks:
  traefik_default:
    external: true
