version: "3.9"

services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    privileged: true
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - VERSION=docker
    expose:
      - 32400
    volumes:
      - /media/eduzen/sambita/media-center/configs/plex:/config
      - /media/eduzen/sambita/media-center/tmp/plex:/transcode
      - /media/eduzen/storage/media-center/downloads/completed/movies:/movies:z
      - /media/eduzen/storage/media-center/downloads/completed/tv:/tv:z
      - /media/eduzen/storage/media-center/downloads/completed/music:/music:z
      - /media/eduzen/storage/media-center/downloads:/downloads:z
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.eduzen.duckdns.org`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls.certresolver=myresolver"
      - "traefik.plex.headers.contentTypeNosniff=true"
      - "traefik.plex.headers.forceSTSHeader=true"
      - "traefik.plex.headers.browserXSSFilter=true"

networks:
  traefik_default:
    external: true
