global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'argon.local'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.22:9100']

  - job_name: 'proxy.local'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.111:9100']

  - job_name: 'um700.local-node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.7:9100']

  - job_name: 'um700.local-traefik'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.7:8088']

  - job_name: 'um700.local-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.7:9090']

  - job_name: 'um700.cadvisor'
    static_configs:
      - targets: ['192.168.1.7:8001']
