---
version: "2.1"

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    restart: unless-stopped
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config:/config
    ports:
      - 8123:8123 #optional
    # devices:
      #- /path/to/device:/path/to/device #optional
