#https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
version: "3"

networks:
  traefik_default:
    external: true

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # network_mode: "host"
    ports:
      - "192.168.1.7:53:53/tcp"
      - "192.168.1.7:53:53/udp"
      - "853:853"
      - "8002:80"
    dns:
      - 127.0.0.1
      - 9.9.9.9
    volumes:
      - '.config/etc-pihole:/etc/pihole'
      - '.config/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    environment:
      TZ: 'Europe/Amsterdam'
      ServerIP: "192.168.1.7"
      WEBPASSWORD: "${PIHOLE_PASSWORD}"
      PIHOLE_DNS_: "9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9;1.1.1.1;1.0.0.1"
      DHCP_ACTIVE: "true"
      DHCP_rapid_commit: "true"
      DNSMASQ_LISTENING: 'all'
      DNSSEC: "true"
      PIHOLE_DOMAIN: "local"
      WEB_PORT: 80
