#https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # network_mode: "host"
    ports:
      - "192.168.1.5:53:53/tcp"
      - "192.168.1.5:53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "88:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: "${PIHOLE_PASSWORD}"
      DNSMASQ_LISTENING: 'all'
      ServerIP: "192.168.1.5"
      PIHOLE_DNS_: "9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9;1.1.1.1;1.0.0.1"
      DNSSEC: "true"
      REV_SERVER: "true"
      PIHOLE_DOMAIN: "local"
      WEB_PORT: 80
      DHCP_rapid_commit: "true"
      PIHOLE_UID: "${PUID}"
      PIHOLE_GID: "${PGID}"
    # Volumes store your data between container upgrades
    volumes:
      - '.config/etc-pihole:/etc/pihole'
      - '.config/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)
