version: "3"

services:
  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1001
      - PGID=1001
      - UMASK=${UMASK}
    volumes:
      - ${CONFIGS}/radarr:/config
      - ${MOVIES}:/movies
      - ${DOWNLOADS}:/downloads
    expose:
      - 7878
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.t480.local`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
