version: "3"

networks:
  traefik_default:
    external: true

services:
  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    volumes:
      - ./configs/radarr:/config
      - /home/eduzen/mounts/seagate/media-center:/media-center:z
    expose:
      - 7878
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.huis.win`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
      - traefik_default

  qb:
    image: ghcr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=80
      - PASSWORD=${QBPASSWORD}
    expose:
      - "80"
    ports:
      - 48072:48072
      - 48072:48072/udp
      - 6882:6881
      - 6882:6881/udp
    volumes:
      - ./configs/qb:/config
      - /home/eduzen/mounts/seagate/media-center/downloads:/downloads:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbmovies.rule=Host(`qb.huis.win`)"
      - "traefik.http.services.qbmovies.loadbalancer.server.port=80"
    networks:
      - traefik_default
