version: "3"

services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    privileged: true 
    restart: always
    ports:
      - 1800:1800
      - 1443:1443
    volumes:
      - "./config/:/opt/deCONZ"
    devices:
      - /dev/ttyACM0 # Conbee2
    environment:
      - TZ=Europe/Amsterdam
      - DECONZ_WEB_PORT=1800
      - DECONZ_WS_PORT=1443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyACM0   # This is the USB device that Conbee II is running on.
      - DECONZ_START_VERBOSE=1
