version: "3.9"

services:
  watchtower:
    image: containrrr/watchtower
    command: --interval 60 --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
