version: "3.9"

services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    command: --interval 960 --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
