version: '3.9'

services:
   jellyfin-rpi4:
      image: ghcr.io/linuxserver/jellyfin:latest
      restart: unless-stopped
      stdin_open: true
      tty: true
      devices:
         # RPi 4
         - /dev/vchiq:/dev/vchiq
      volumes:
         - /media/eduzen/storage/media-center/configs/jellyfin-rpi4:/config
         - /media/eduzen/storage/media-center/downloads/completed/music:/music:z
         - /media/eduzen/storage/media-center/downloads/completed/movies:/movies:z
         - /media/eduzen/storage/media-center/downloads/completed/tv:/tv:z
      expose:
         - 8096
      labels:
         - "traefik.enable=true"
         - "traefik.http.routers.jellyfin-rpi4.rule=Host(`jrpi4.eduzen.duckdns.org`)"
         - "traefik.http.routers.jellyfin-rpi4.entrypoints=websecure"
         - "traefik.http.routers.jellyfin-rpi4.tls.certresolver=myresolver"
         - "traefik.http.routers.jellyfin-rpi4.middlewares=jellyfin-mw-rpi4"
         - "traefik.http.services.jellyfin-rpi4.loadbalancer.server.port=8096"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.SSLRedirect=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.SSLForceHost=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.STSSeconds=315360000"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.STSIncludeSubdomains=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.STSPreload=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.forceSTSHeader=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.frameDeny=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.contentTypeNosniff=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.browserXSSFilter=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.customFrameOptionsValue='allow-from https://jrpi4.eduzen.duckdns.org'"
      networks:
         - traefik_default
      environment:
         - TZ=Europe/Amsterdam
         - PUID=1000
         - PGID=1000
         - UMASK=022
         - JELLYFIN_PublishedServerUrl=jrpi4.eduzen.duckdns.org

networks:
  traefik_default:
    external: true
