version: '3.9'

services:
   jellyfin-rpi4:
      image: ghcr.io/linuxserver/jellyfin:latest
      restart: unless-stopped
      stdin_open: true
      tty: true
      devices:
         # RPi 4
         - /dev/vchiq:/dev/vchiq
      volumes:
         - ${CONFIGS}/jellyfin-rpi4:/config
         - ${MUSIC}:/music:z
         - ${MOVIES}:/movies:z
         - ${TV}:/tv:z
      expose:
         - 8096
      labels:
         - "traefik.enable=true"
         - "traefik.http.routers.jrpi4.rule=Host(`jrpi4.${DOMAIN}`)"
         - "traefik.http.routers.jrpi4.entrypoints=websecure"
         - "traefik.http.routers.jrpi4.tls.certresolver=myresolver"
         - "traefik.http.services.jrpi4.loadbalancer.server.port=8096"
         - "traefik.jrpi4.headers.contentTypeNosniff=true"
         - "traefik.jrpi4.headers.forceSTSHeader=true"
         - "traefik.jrpi4.headers.browserXSSFilter=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.SSLRedirect=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.SSLForceHost=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.STSSeconds=315360000"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.STSIncludeSubdomains=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.STSPreload=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.forceSTSHeader=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.frameDeny=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.contentTypeNosniff=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.browserXSSFilter=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.customFrameOptionsValue='allow-from https://jrpi4.${DOMAIN}'"
      networks:
         - traefik_default
      environment:
         - TZ=${TZ}
         - PUID=${PUID}
         - PGID=${PGID}
         - UMASK=${UMASK}
         - JELLYFIN_PublishedServerUrl=jrpi4.${DOMAIN}

networks:
  traefik_default:
    external: true
