version: "3"

services:
   adguard:
     image: adguard/adguardhome:latest
     restart: unless-stopped
     container_name: adguardhome
     #network_mode: host
     volumes:
       - ./config/work:/opt/adguardhome/work
       - ./config/conf:/opt/adguardhome/conf
       - /etc/localtime:/etc/localtime:ro
     ports:
       - "53:53/tcp"
       - "53:53/udp"
       - "80:80/tcp"
       - "3000:3000/tcp"
