version: "3"

networks:
  traefik_default:
    external: true

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/workdir:/opt/adguardhome/work
      - ./config/confdir:/opt/adguardhome/conf
    #ports:
      #      - 53:53/tcp
      #- 53:53/udp
      #- 67:67/udp

      #- 68:68/udp
      #- 80:80/tcp
      #- 443:443/tcp
      #- 443:443/udp
      #- 3000:3000/tcp
      #- 853:853/tcp
      #- 784:784/udp
      #- 853:853/udp
      #- 8853:8853/udp
      #- 5443:5443/tcp
      #- 5443:5443/udp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed

    #network_mode: "host"
    #environment:
    #  ServerIP: "192.168.1.7"
    #  WEBPASSWORD: "${PIHOLE_PASSWORD}"
    #  PIHOLE_DNS_: "9.9.9.9;149.112.112.112;2620:fe::fe;2620:fe::9;1.1.1.1;1.0.0.1"
    #  DHCP_ACTIVE: "true"
    #  DHCP_rapid_commit: "true"
    #  DNSMASQ_LISTENING: 'all'
    #  DNSSEC: "true"
    #  PIHOLE_DOMAIN: "local"
    #  WEB_PORT: 80
