version: '3'

services:

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117
    expose:
      - 9117
    volumes:
      - ./config/jackett:/config
      - ${DOWNLOADS}/blackhole:/downloads:z
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - AUTO_UPDATE=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.t480.local`)"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
