version: '3'

services:

  jackett:
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ${CONFIGS}/jackett:/config
      - ${DOWNLOADS}:/downloads
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - AUTO_UPDATE=true
