version: '3'

services:

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ./config/jackett:/config
      - ${DOWNLOADS}/blackhole:/downloads:z
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - AUTO_UPDATE=true
