version: "3.9"

networks:
  traefik_default:
    external: true

services:
  nginx:
    image: nginx:1.20.1-alpine
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST="ha.eduzen.duckdns.org"
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`ha.eduzen.duckdns.org`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      # - "traefik.http.routers.nginx.middlewares=auth"
      # - "traefik.http.middlewares.auth.basicauth.users=test:$$2y$$12$$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG"
    networks:
      - traefik_default
