version: "3.9"
services:
  calibre:
    image: ghcr.io/linuxserver/calibre:version-v5.25.0
    container_name: calibre
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - PASSWORD= #optional
      # - CLI_ARGS= #optional
    volumes:
      - ${CONFIGS}/calibre/:/config
      - ${CONFIGS}/library:/books
      - ${TMP}:/tmp
    ports:
      # - 53:53/udp
      - 8080:8080
      - 8081:8081

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${CONFIGS}/calibre/web/:/config
      - ${CONFIGS}/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
