version: '3.9'

services:

   jellyfin:
      image: jellyfin/jellyfin:latest
      restart: unless-stopped
      stdin_open: true
      tty: true
      user: 1001:1001
      group_add:
         - 1001
         - 122
      devices:
         # VAAPI Devices (examples)
         - "/dev/dri:/dev/dri"
      ports:
         - 8096:8096
         - 8920:8920 #optional
         - 7359:7359/udp #optional
         - 1900:1900/udp #optional
      environment:
         - TZ=${TZ}
         - JELLYFIN_PublishedServerUrl=t480.local
      volumes:
         - ${CONFIGS}/jellyfin:/config
         - ${DOWNLOADS}:/data:z
         - ${MOVIES}:/movies:z
         - ${TV}:/tv:z
