version: '2.3'

services:

   jellyfin:
      image: ghcr.io/linuxserver/jellyfin:latest
      restart: unless-stopped
      stdin_open: true
      tty: true
      runtime: nvidia
      devices:
         - "/dev/dri:/dev/dri"
      networks:
         - traefik_default
      expose:
         - 8096
      labels:
         - "traefik.enable=true"
         - "traefik.http.routers.jrpi4.rule=Host(`jelly.t480.local`) || Host(`tv.eduzen.ar`)"
         - "traefik.http.routers.jrpi4.entrypoints=websecure"
         - "traefik.http.routers.jrpi4.tls.certresolver=myresolver"
         - "traefik.http.services.jrpi4.loadbalancer.server.port=8096"
         - "traefik.jrpi4.headers.contentTypeNosniff=true"
         - "traefik.jrpi4.headers.forceSTSHeader=true"
         - "traefik.jrpi4.headers.browserXSSFilter=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.SSLRedirect=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.SSLForceHost=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.STSSeconds=315360000"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.STSIncludeSubdomains=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.STSPreload=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.forceSTSHeader=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.frameDeny=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.contentTypeNosniff=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.browserXSSFilter=true"
         - "traefik.http.middlewares.jellyfin-mw-rpi4.headers.customFrameOptionsValue='allow-from https://jelly.t480.local'"
      environment:
         - TZ=${TZ}
         - PUID=${PUID}
         - PGID=${PGID}
         - UMASK=${UMASK}
         - NVIDIA_VISIBLE_DEVICES=all
         - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
         - JELLYFIN_PublishedServerUrl=jelly.${DOMAIN}
      volumes:
         - ${CONFIGS}/jellyfin:/config
         - ${DOWNLOADS}:/data:z
         - ${MOVIES}:/movies:z
         - ${TV}:/tv:z

networks:
  traefik_default:
    external: true
