version: '3.9'

services:

   jellyfin:
      image: jellyfin/jellyfin:latest
      restart: unless-stopped
      stdin_open: true
      tty: true
      devices:
         # VAAPI Devices (examples)
         - "/dev/dri:/dev/dri"
      networks:
         - traefik_default
      expose:
         - 8096
      labels:
         - "traefik.enable=true"
         - "traefik.http.routers.jelly.rule=Host(`jelly.huis`)"
         - "traefik.http.services.jelly.loadbalancer.server.port=8096"
      environment:
         - TZ=${TZ}
         - JELLYFIN_PublishedServerUrl=jelly.huis
      volumes:
         - ./config:/config
         - ${DOWNLOADS}:/data:z
         - ${MOVIES}:/movies:z
         - ${TV}:/tv:z

networks:
  traefik_default:
    external: true
