version: "3.9"

services:

   jellyfin:
      image: jellyfin/jellyfin:latest
      restart: unless-stopped
      stdin_open: true
      tty: true
      group_add: # by id as these may not exist within the container. Needed to provide permissions to the VAAPI Devices
         - "107" #render
         - "44" #video
      devices:
         # VAAPI Devices (examples)
         - "/dev/dri:/dev/dri"
         - "/dev/dri/renderD128:/dev/dri/renderD128"
      ports:
         - 8096:8096
      environment:
         - TZ=Europe/Amsterdam
         - JELLYFIN_PublishedServerUrl=jelly.huis.win
         - JELLYFIN_CONFIG_DIR=/config
      volumes:
         - ./config:/config
         - /home/eduzen/mounts/:/media:z
