version: '2.3'

services:

   jellyfin:
      image: ghcr.io/linuxserver/jellyfin:latest
      restart: unless-stopped
      stdin_open: true
      tty: true
      runtime: nvidia
      devices:
         - "/dev/dri:/dev/dri"
      ports:
         - 8096:8096
         - 8920:8920 #optional
         - 7359:7359/udp #optional
         - 1900:1900/udp #optional
      environment:
         - TZ=Europe/Amsterdam
         - PUID=1000
         - PGID=1000
         - UMASK=022
         - NVIDIA_VISIBLE_DEVICES=all
         - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
         - JELLYFIN_PublishedServerUrl=jelly.eduzen.duckdns.org
      volumes:
         - ./config/jellyfin:/config
         - ${DOWNLOADS}:/data:z
         - ${MOVIES}:/movies:z
         - ${TV}:/tv:z
