version: "3.9"

services:
  # Bazarr is a companion application to Sonarr and Radarr.
  # It can manage and download subtitles based on your requirements.
  # You define your preferences by TV show or movie and Bazarr takes care of everything for you.
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    volumes:
      - ./config:/config
      - /home/eduzen/mounts/seagate/media-center/movies:/movies:z
      - /home/eduzen/mounts/storage/media-center/series:/tv:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.huis.win`)"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    expose:
      - 6767
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
