version: "3.9"

services:
  # Bazarr is a companion application to Sonarr and Radarr.
  # It can manage and download subtitles based on your requirements.
  # You define your preferences by TV show or movie and Bazarr takes care of everything for you.
  bazarr:
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1001
      - PGID=1001
      - UMASK=022
    volumes:
      - ./config:/config
      - ${MOVIES}:/movies
      - ${TV}:/tv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.t480.local`)"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    expose:
      - 6767
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
