version: "2.1"

services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=$PUID
      - PGID=$PGID
      - MEM_LIMIT=1024M #optional
      - MEM_STARTUP=1024M #optional
    volumes:
      - .config/:/config
