version: "2.1"

services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:7.1.68
    restart: unless-stopped
    container_name: unifi-controller
    security_opt:
      - no-new-privileges:true
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/:/config
