version: "2.1"

services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MEM_LIMIT=1024M #optional
      - MEM_STARTUP=1024M #optional
    volumes:
      - .config/:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8089:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
