version: "3"

networks:
  traefik_default:
    external: true

services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:7.1.68
    container_name: unifi-controller
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PUID=$PUID
      - PGID=$PGID
      # - MEM_LIMIT=2024 #optional
      # - MEM_STARTUP=1024 #optional
    volumes:
      - ./config/:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 1900:1900/udp #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    expose:
      - 8080
      - 8443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.rule=Host(`unifi.huis.win`)"
      - "traefik.http.services.unifi.loadbalancer.server.port=8433"
    networks:
      - traefik_default
