version: '3'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.25.1
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
    devices:
      - /dev/ttyACM0 # Conbee2
    ports:
      - 9090:9090
    network_mode: host
