version: "3.9"

services:
   medusa:
    image: ghcr.io/linuxserver/medusa
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
    volumes:
      - ./config:/config
      - ${DOWNLOADS}:/downloads
      - ${TV}:/tv
    ports:
      - 8081:8081
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
