version: "3.8"

services:
  qbittorrent:
    image: eduzen/filmer:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK=022
      - WEBUI_PORT=80
    expose:
      - "80"
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./configs/filmer:/config
      - /media/eduzen/storage/media-center/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filmer.rule=Host(`eduzen.duckdns.org`)"
      - "traefik.http.routers.filmer.entrypoints=websecure"
      - "traefik.http.routers.filmer.tls.certresolver=myresolver"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
