version: "3.8"

services:
  qbittorrent:
    image: eduzen/filmer:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=80
    expose:
      - "80"
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ${CONFIGS}/filmer:/config
      - ${DOWNLOADS}/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filmer.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.filmer.entrypoints=websecure"
      - "traefik.http.routers.filmer.tls.certresolver=myresolver"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
